server:
  servlet:
    context-path: /MPSSchool
#server:
#  port: 9001
spring:
  datasource:
    url: jdbc:mysql://192.168.0.102:3306/microservices
    username: sandeep
    password: sandeep
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#----------------below logging will activate the jpa transactional log
#actuator endpoint managemnet
management:
  endpoint:
    shutdown:
      enabled: true
    beans:
      enabled: true
    env:
      enabled: true


logging:
  charset:
    file: /opt/tomcat/apache-tomcat-10.1.16/logs/ska-app.log
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG

