spring.application.name=SManagement
spring.flyway.enabled=false

#Database Configuration for postgreSQL
spring.datasource.url=jdbc:postgresql://192.168.0.102:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# IMPORTANT ? to use stud1 schema
spring.jpa.properties.hibernate.default_schema=db001

##################Kafka Schema Registry###########################
spring.kafka.bootstrap-servers=192.168.0.102:9092
#***********************Producer Configuration*********************
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
#Prevents class-name leakage ? better for cross-language consumers.



#***********************Producer Configuration*********************

spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.smanagement.dto.NotificationEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=com.smanagement.dto


# IMPORTANT ? to auto-create tables
spring.jpa.hibernate.ddl-auto=update

# Logging (optional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

#Kafka Configuration
kafka.psl.topic_name=student_topic
kafka.psl.group-id=student-consumer-group